### ISSUE TITLE
Places and Reloading

### ISSUE THREAD

**Issue by megadr01d** [nao-pon/elFinder-nightly#13]
I can't find a clear pattern for this bug but adding a couple of folders to the Places section, then accessing one of them and hitting the Reload button makes the other folders disappear from Places.

After adding/accessing/removing some folders, sometimes the Root drive also shows the same content as Places instead of the actual folders in root. I have to click on the Root drive in the navbar to update the contents.

Using Local File System on 2.1.

**Comment by nao-pon** [comment]
@megadr01d I pushed new version. try that new one.

**Comment by megadr01d** [comment]
Hm, still not working correctly in the latest push.
Check [this](http://microvoid.in/repo/private/temp/places.mp4) screencast to understand the problem. This is in Safari 7.1.6.

**Comment by nao-pon** [comment]
I couldn't see missing problem with step by step. But remake tree problem was fixed on  https://github.com/Studio-42/elFinder/commit/f234f03c71ac441eee0fcc3dd74a6ec4800e1ede. Please re-check with browser cache clearing.

**Comment by megadr01d** [comment]
@nao-pon I updated to the latest d499cb9, updated to jQuery/jQuery UI: 2.1.4/1.11.4 (was still using 1.8.0/1.8.23, cleared the cache more than once (although, I usually do after updating the nightly) and corrected a modification I had on my side and everything is working correctly now.

Thanks for the patience.
